<a href="https://colab.research.google.com/github/vineet1947/general_code-_files-/blob/main/simple_neural_net.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import tensorflow as tf

In [12]:
from tensorflow import keras


In [13]:
l0 = tf. keras.layers.Dense(units=  4  , input_shape  = [1]) 
l1 = tf.keras.layers.Dense(units = 4) 
l2 = tf.keras.layers.Dense(units = 1)

In [14]:
model = tf.keras.Sequential([l0 , l1 ,  l2]) 
model.compile(loss = 'mean_squared_error' , optimizer = tf.keras.optimizers.Adam(0.1) )

In [15]:
import numpy as np

In [16]:
celcius = np.array([-40 ,  -10 , 0 , 8 , 15  , 22 , 38] , dtype= float) 
far = np.array([-40 ,  14 , 32, 46 , 59 , 72 , 100] , dtype  = float )

In [19]:
model.fit(celcius  , far  , epochs = 500 , verbose = False)

In [21]:
model.predict([100])

array([[211.74744]], dtype=float32)

In [22]:
l0.get_weights()

[array([[-0.18372269,  0.531092  , -0.0732225 ,  0.29199383]],
       dtype=float32),
 array([-0.597703 ,  3.7986794, -1.6525108,  3.2896533], dtype=float32)]

In [26]:
l1.get_weights()

[array([[ 0.30075464, -0.7102446 , -0.07773702, -0.03927414],
        [ 0.7790308 , -0.28473753,  0.0844007 , -1.0468776 ],
        [-0.47514254,  0.6858956 , -0.5703187 ,  0.20308785],
        [-0.11247142,  1.1141406 ,  1.0506816 , -0.33224645]],
       dtype=float32),
 array([ 3.1607425,  1.5175419,  3.632065 , -3.6449358], dtype=float32)]

In [25]:
l2.get_weights()

[array([[ 0.8319738],
        [ 0.6633072],
        [ 0.9492451],
        [-1.4264405]], dtype=float32), array([3.5670154], dtype=float32)]